[package]
name = "pc-trainer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.18.1"
sdl2 = "0.35.2"
array2d = "0.2.1"
rand = "0.8.5"
queues = "1.0.2"